name: Deploy Terraform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build_job:
    runs-on: ubuntu-latest
    environment: dev #Should be changed, lol
    defaults:
      run:
        working-directory: ./terraform
    
    env:
      ARM_CLIENT_ID: "${{ secrets.AKSHOSTING_DEV_CLIENT_ID }}"
      ARM_SUBSCRIPTION_ID: "${{ secrets.AKSHOSTING_DEV_SUBSCRIPTION_ID }}"
      ARM_TENANT_ID: "${{ secrets.AKSHOSTING_DEV_TENANT_ID }}"
      ARM_USE_AZUREAD: true
      ENVIRONMENT_NAME: dev

    steps:
    - uses: actions/checkout@v3

    - name: Install Terraform
      run: bash "${{ github.workspace }}/.github/scripts/install_terraform.sh" 

    - name: Terraform Fmt
      run: terraform fmt -check

    - name: Terraform Init
      run: |
        terraform init \
        -backend-config=resource_group_name="${{ secrets.AKSHOSTING_DEV_TFSTATE_RESOURCE_GROUP_NAME }}" \
        -backend-config=storage_account_name="${{ secrets.AKSHOSTING_DEV_TFSTATE_STORAGE_ACCOUNT_NAME }}" \
        -backend-config=container_name="${{ secrets.AKSHOSTING_DEV_TFSTATE_STORAGE_CONTAINER_NAME }}" \
        -backend-config=key="akshosting.${{ env.ENVIRONMENT_NAME }}.tfstate"
        
    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -var-file="envs/dev.tfvars" -out=tfplan #UPDATE VARS file

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve tfplan